language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
  - docker tag udagram-api-feed ducathtla/udagram-api-feed:latest
  - docker tag udagram-api-user ducathtla/udagram-api-user:lastest
  - docker tag udagram-frontend ducathtla/udagram-frontend:lastest
  - docker tag reverseproxy ducathtla/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ducathtla/udagram-api-feed:latest
  - docker push ducathtla/udagram-api-user:lastest
  - docker push ducathtla/udagram-frontend:lastest
  - docker push ducathtla/reverseproxy:latest
